question_data = [
    {"category": "Science", "type": "boolean", "difficulty": "medium", "question": "Lightning is hotter than the surface of the sun.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "medium", "question": "The Great Fire of London occurred in 1666.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment", "type": "boolean", "difficulty": "medium", "question": "The movie 'Inception' was directed by Christopher Nolan.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium", "question": "The currency of Japan is the Yen.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science", "type": "boolean", "difficulty": "medium", "question": "Water boils at 100 degrees Celsius at sea level.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "medium", "question": "Neil Armstrong was the first person to walk on the moon.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "medium", "question": "Mount Everest is the tallest mountain in the world.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment", "type": "boolean", "difficulty": "medium", "question": "The Harry Potter book series was written by J.K. Rowling.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium", "question": "The capital of Australia is Sydney.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science", "type": "boolean", "difficulty": "medium", "question": "Humans have 206 bones in their body.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "medium", "question": "World War II ended in 1945.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "medium", "question": "The Sahara Desert is the largest desert in the world.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment", "type": "boolean", "difficulty": "medium", "question": "The character 'Sherlock Holmes' was created by Arthur Conan Doyle.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium", "question": "A leap year has 366 days.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science", "type": "boolean", "difficulty": "medium", "question": "The chemical symbol for gold is Au.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "medium", "question": "The Titanic sank in 1912.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "medium", "question": "Africa is the largest continent on Earth.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment", "type": "boolean", "difficulty": "medium", "question": "The Beatles were a British rock band.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium", "question": "The Eiffel Tower is located in Berlin.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science", "type": "boolean", "difficulty": "medium", "question": "Humans share approximately 60% of their DNA with bananas.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "medium", "question": "The Berlin Wall fell in 1991.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "medium", "question": "Canada has the longest coastline of any country.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment", "type": "boolean", "difficulty": "medium", "question": "The movie 'Titanic' won 11 Academy Awards.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium", "question": "There are 9 planets in the Solar System.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science", "type": "boolean", "difficulty": "medium", "question": "Albert Einstein developed the theory of relativity.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "medium", "question": "The Cold War was primarily a conflict between the USA and China.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "medium", "question": "The Amazon River is the longest river in the world.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment", "type": "boolean", "difficulty": "medium", "question": "'Frozen' was released by DreamWorks Animation.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium", "question": "A heptagon has 8 sides.", "correct_answer": "False", "incorrect_answers": ["True"]},

   
]
